<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTDrmLAy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTDrmLAy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTDrmLAy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTDrmLAy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTDrmLAy\App_KernelDevDebugContainer([
    'container.build_hash' => 'TDrmLAy',
    'container.build_id' => 'c04f80f7',
    'container.build_time' => 1586418337,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTDrmLAy');
